run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/cheggaaa/pb/v3
          - github.com/buger/jsonparser
          - github.com/spf13/pflag
          - github.com/google/uuid
          - github.com/EvgenyRomanov/otus_go_hw/hw12_13_14_15_calendar/internal/storage
          - github.com/EvgenyRomanov/otus_go_hw/hw12_13_14_15_calendar/internal/server/http/response
          - github.com/EvgenyRomanov/otus_go_hw/hw12_13_14_15_calendar/internal/app
          - github.com/EvgenyRomanov/otus_go_hw/hw12_13_14_15_calendar/internal/logger
          - github.com/EvgenyRomanov/otus_go_hw/hw12_13_14_15_calendar/internal/server/http
          - github.com/EvgenyRomanov/otus_go_hw/hw12_13_14_15_calendar/internal/server/pb
          - github.com/EvgenyRomanov/otus_go_hw/hw12_13_14_15_calendar/internal/server/grpc
          - github.com/cenkalti/backoff
          - github.com/streadway/amqp
          - github.com/EvgenyRomanov/otus_go_hw/hw12_13_14_15_calendar/pkg/rmq
          - github.com/pressly/goose
          - github.com/gorilla/mux
          - github.com/spf13/viper
          - github.com/lib/pq
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify
          - github.com/google/uuid
          - github.com/EvgenyRomanov/otus_go_hw/hw12_13_14_15_calendar/internal/storage
          - github.com/EvgenyRomanov/otus_go_hw/hw12_13_14_15_calendar/internal/server/http/response
          - github.com/EvgenyRomanov/otus_go_hw/hw12_13_14_15_calendar/internal/server/pb
          - github.com/golang/protobuf/ptypes/timestamp
          - github.com/lib/pq
          - github.com/pressly/goose
          - github.com/gorilla/mux
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
  exclude-dirs:
    - ../../../../go
    - ../../../../../../opt/hostedtoolcache/go
    - hw12_13_14_15_calendar/internal/server/pb

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
